apiVersion: v1
kind: Pod
metadata:
  name: ebs-test-pod2
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a 
  containers:
  - name: app
    image: nginx


    volumeMounts:
    - mountPath: /data
      name: data

  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: ebs-gp3-test-3
