apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-with-pv
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["/bin/sh", "-c"]
    args: ["sleep 3600"]


    volumeMounts:
    - name: xxxxxxxxx
      mountPath: /data


  volumes:
  - name: random-name
    persistentVolumeClaim:
      claimName: demo-pvc
